//! Generated from tools/upstream_currencies.py.
//! Source commit: scrapinghub/price-parser ea535c0.
//! Do not edit by hand; run `python3 tools/generate_currency_data.py`.

pub static SAFE_CURRENCY_SYMBOLS: &[&str] = &[
    "Bds$",
    "CUC$",
    "MOP$",
    "AR$",
    "AU$",
    "BN$",
    "BZ$",
    "CA$",
    "CL$",
    "CO$",
    "CV$",
    "HK$",
    "MX$",
    "NT$",
    "NZ$",
    "TT$",
    "RD$",
    "WS$",
    "US$",
    "$U",
    "C$",
    "J$",
    "N$",
    "R$",
    "S$",
    "T$",
    "Z$",
    "A$",
    "SY£",
    "LB£",
    "CN¥",
    "GH₵",
    "$",
    "€",
    "£",
    "zł",
    "Zł",
    "Kč",
    "₽",
    "¥",
    "￥",
    "฿",
    "դր.",
    "դր",
    "₦",
    "₴",
    "₱",
    "৳",
    "₭",
    "₪",
    "﷼",
    "៛",
    "₩",
    "₫",
    "₡",
    "টকা",
    "ƒ",
    "₲",
    "؋",
    "₮",
    "नेरू",
    "₨",
    "₶",
    "₾",
    "֏",
    "ރ",
    "৲",
    "૱",
    "௹",
    "₠",
    "₢",
    "₣",
    "₤",
    "₧",
    "₯",
    "₰",
    "₳",
    "₷",
    "₸",
    "₹",
    "₺",
    "₼",
    "₾",
    "₿",
    "ℳ",
    "ر.ق.‏",
    "د.ك.‏",
    "د.ع.‏",
    "ر.ع.‏",
    "ر.ي.‏",
    "ر.س.‏",
    "د.ج.‏",
    "د.م.‏",
    "د.إ.‏",
    "د.ت.‏",
    "د.ل.‏",
    "ل.س.‏",
    "د.ب.‏",
    "د.أ.‏",
    "ج.م.‏",
    "ل.ل.‏",
    " تومان",
    "تومان",
    "درهم",
    "ريال",
    "جنيه",
    "EUR",
    "euro",
    "eur",
    "CHF",
    "DKK",
    "Rp",
    "lei",
    "руб.",
    "руб",
    "грн.",
    "грн",
    "дин.",
    "Dinara",
    "динар",
    "лв.",
    "лв",
    "р.",
    "тңг",
    "тңг.",
    "ман.",
];
pub static CURRENCY_CODES: &[&str] = &[
    "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AFL", "AZN", "BAM", "BDT",
    "BBD", "BGN", "BHD", "BIF", "BSD", "BMD", "BND", "BOB", "BOV", "BRL", "BTN", "BWP", "BYN",
    "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC", "CUC",
    "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EEK", "EGP", "ERN", "ETB", "EUR", "FJD",
    "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK",
    "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY",
    "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD",
    "LSL", "LTL", "LVL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR",
    "MVR", "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "PRB", "NZD",
    "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF",
    "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STD", "SVC",
    "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TVD", "TWD", "TZS", "UAH",
    "UGX", "USD", "USN", "UYI", "UYU", "UZS", "VEF", "VND", "VUV", "WST", "XAF", "XAG", "XAU",
    "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA",
    "XXX", "YER", "ZAR", "ZMK", "ZMW", "ZWD", "ZWL", "NTD", "RMB", "ATS", "BEF", "CYP", "DEM",
    "NLG", "FIM", "FRF", "GRD", "IEP", "ITL", "LUF", "MTL", "PTE", "SKK", "SIT", "ESP", "VAL",
];
pub static OTHER_CURRENCY_SYMBOLS: &[&str] = &[
    "tolarjev", "D-Mark", "Bs.F.", "SL Re", "Sucre", "kroon", "Afl.", "FCFA", "FrCD", "MURs",
    "NPRs", "PKRs", "Ptas", "SLRs", "din.", "litų", "man.", "Δρχ.", "ریال", "AED", "AFL", "AFN",
    "ALL", "AMD", "ANG", "AOA", "ARS", "ATS", "AUD", "AWG", "AZN", "B/.", "BAM", "BBD", "BDT",
    "BEF", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN",
    "BZD", "CAD", "CDF", "CFA", "CFP", "CHE", "CHW", "CLF", "CLP", "CNY", "COP", "COU", "CRC",
    "CUC", "CUP", "CVE", "CYP", "CZK", "DEM", "DJF", "DOP", "DZD", "Dkr", "EEK", "EGP", "ERN",
    "ESP", "ETB", "FBu", "FIM", "FJD", "FKP", "FRF", "Fdj", "Fr.", "GBP", "GEL", "GGP", "GHS",
    "GIP", "GMD", "GNF", "GRD", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "IEP",
    "ILS", "IMP", "INR", "IQD", "IRR", "IR£", "ISK", "ITL", "Ikr", "JEP", "JMD", "JOD", "JPY",
    "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "Ksh", "LAK", "LBP", "LEI",
    "LKR", "LRD", "LSL", "LTL", "LUF", "LVL", "LYD", "Lei", "Lek", "MAD", "MDL", "MGA", "MKD",
    "MMK", "MNT", "MOP", "MRO", "MRf", "MTL", "MTn", "MUR", "MVR", "MWK", "MXN", "MXV", "MYR",
    "MZN", "NAD", "NGN", "NIO", "NLG", "NOK", "NPR", "NTD", "NZD", "Nfk", "Nkr", "Nu.", "OMR",
    "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PRB", "PTE", "PYG", "Pta", "Pts", "QAR", "RMB",
    "RON", "RSD", "RUB", "RWF", "S/.", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SIT",
    "SKK", "SLL", "SOS", "SRD", "SSP", "STD", "SVC", "SYP", "SZL", "Skr", "Ssh", "THB", "TJS",
    "TMT", "TND", "TOP", "TRY", "TSh", "TTD", "TVD", "TWD", "TZS", "UAH", "UGX", "USD", "USN",
    "USh", "UYI", "UYU", "UZS", "VAL", "VEF", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA",
    "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "YER",
    "ZAR", "ZMK", "ZMW", "ZWD", "ZWL", "fl.", "fr.", "leu", "mk.", "pln", "Δρ.", "Af", "BD", "Br",
    "Bs", "CF", "DA", "DM", "DT", "Db", "FC", "FG", "FR", "Ft", "JD", "KD", "KM", "Kz", "LD", "Le",
    "Lm", "Ls", "Lt", "MK", "Pt", "QR", "RM", "Rf", "Rs", "SR", "Sk", "TL", "Tk", "UF", "UM", "VT",
    "YR", "ZK", "kn", "kr", "öS", "đ", "Р", "р", "र", "円", "원",
];
